---
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
  proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=myemail@example.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
  whoami:
    image: traefik/whoami
    command:
      # It tells whoami to start listening on 2001 instead of 80
      - --port=2001
      - --name=iamfoo
    ports:
      - "2001:2001"
    environment:
      - LETSENCRYPT_HOST=whoami-47-129-135-201.xip.softsquaregroup.app
      - VIRTUAL_HOST=whoami-47-129-135-201.xip.softsquaregroup.app
      - VIRTUAL_PORT=2001
volumes:
  acme:
  certs:
  html: