---
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./public_html:/usr/share/nginx/html
      - ./static-file/static_location.conf:/etc/nginx/vhost.d/static-192-168-1-122.xip.softsquaregroup.app_location
      # - ../fullchain.cer:/etc/nginx/ssl/xip.softsquaregroup.app.crt
      # - ../xip.softsquaregroup.app.key:/etc/nginx/ssl/xip.softsquaregroup.app.key

  whoami:
    image: traefik/whoami
    command:
      - --name=iamwebsite
    # ports:
    #   - "2001:80"
    environment:
      - VIRTUAL_HOST=static-192-168-1-122.xip.softsquaregroup.app
      - VIRTUAL_PORT=80
  
